apiVersion: apps/v1
kind: Deployment
metadata:
  name: polarity
spec:
  replicas: 1
  selector:
    matchLabels:
      app: polarity
  template:
    metadata:
      labels:
        app: polarity
    spec:
      containers:
      - name: polarity-app
        # Change image path to your respectively built image
        image: us-west1-docker.pkg.dev/project-756/sentiment-repo/polarity:latest 
        ports:
        - containerPort: 8080
        env:
          - name: PORT
            value: "8080"
