apiVersion: apps/v1
kind: Deployment
metadata:
  name: subjectivity
spec:
  replicas: 1
  selector:
    matchLabels:
      app: subjectivity
  template:
    metadata:
      labels:
        app: subjectivity
    spec:
      containers:
      - name: subjectivity-app
        # Change image path to your respectively built image
        image: us-west1-docker.pkg.dev/project-756/sentiment-repo/subjectivity:latest
        ports:
        - containerPort: 8080
        env:
          - name: PORT
            value: "8080"
